# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultItemReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GraphMap', models.CharField(max_length=100000, verbose_name='\u5bf9\u5e94\u9891\u8c31')),
                ('CriterionBuiltIds', models.CharField(max_length=100000, verbose_name='\u5224\u636e\u6784\u5efaID')),
                ('CompCode', models.CharField(max_length=50, verbose_name='\u6545\u969c\u8bbe\u5907\u7f16\u53f7')),
                ('RRId', models.IntegerField(verbose_name='\u8fd0\u884c\u6b21\u6570')),
            ],
            options={
                'db_table': 'FaultItemReport',
                'verbose_name': '\u6545\u969c\u9876\u62a5\u544a',
                'verbose_name_plural': '\u6545\u969c\u9876\u62a5\u544a',
            },
        ),
        migrations.CreateModel(
            name='GraphArchives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(verbose_name='\u7f16\u53f7')),
                ('DataStr', models.CharField(max_length=100000, verbose_name='\u6570\u636e1')),
                ('FeatureStr', models.CharField(max_length=100000, verbose_name='\u6570\u636e2')),
            ],
            options={
                'db_table': 'GraphArchives',
                'verbose_name': '\u9891\u8c31\u56fe',
                'verbose_name_plural': '\u9891\u8c31\u56fe',
            },
        ),
        migrations.CreateModel(
            name='InferComboReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField(verbose_name='\u7f16\u53f7')),
                ('DisplayText', models.CharField(max_length=50, verbose_name='\u6545\u969c\u63cf\u8ff0')),
                ('CompCode', models.CharField(max_length=100, verbose_name='\u6545\u969c\u8bbe\u5907\u7f16\u53f7')),
                ('RtDatas', models.CharField(max_length=100, verbose_name='\u6545\u969c\u51fa\u73b0\u7684\u9891\u8c31\u56fe\u4f4d\u7f6e')),
                ('RRId', models.IntegerField(verbose_name='\u8fd0\u884c\u6b21\u6570')),
            ],
            options={
                'db_table': 'InferComboReport',
                'verbose_name': '\u7ec4\u5408\u63a8\u65ad\u62a5\u544a',
                'verbose_name_plural': '\u7ec4\u5408\u63a8\u65ad\u62a5\u544a',
            },
        ),
    ]
