"""
Django settings for testproject project.

Generated by 'django-admin startproject' using Django 1.9.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0,os.path.join(BASE_DIR,'apps'))
sys.path.insert(0,os.path.join(BASE_DIR,'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd4=tgbg)29-r=q+h#(s0p$!%k+=c#d5g5(4!9jzd%hu4+@4o(k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# TEMPLATE_DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pure_pagination',
    'xadmin',
    'crispy_forms',
    'users',
    'pump',
    'spectrum',
]
AUTH_USER_MODEL = 'users.UserProfile'
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 4,
    'MARGIN_PAGES_DISPLAYED': 2,
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'testproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': "djangomysql",
#         'USER':"root",
#         'PASSWORD':"789635241",
#         'HOST':"127.0.0.1",
#     }
# }
DATABASES = {
    'default': {
         'ENGINE': 'sql_server.pyodbc',
         'NAME': 'test',
         'USER': 'sa',
         'PASSWORD': '789635241',
         'HOST': '127.0.0.1',
         'PORT': '',
         'OPTIONS': {
              'driver':'SQL Server Native Client 11.0',
              'MARS_Connection': True,
         },
     },
    'test1':{
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'test1',
        'USER': 'sa',
        'PASSWORD': '789635241',
        'HOST': '127.0.0.1',
        'PORT': '',
        'OPTIONS': {
            'driver':'SQL Server Native Client 11.0',
            'MARS_Connection': True,
         },
    },
    'PumpSystem':{
        'ENGINE': 'sql_server.pyodbc',
        'NAME': 'PumpSystemV2.1.4',
        'USER': 'sa',
        'PASSWORD': '789635241',
        'HOST': '127.0.0.1',
        'PORT': '',
        'OPTIONS': {
            'driver':'SQL Server Native Client 11.0',
            'MARS_Connection': True,
         },
    }

}


# use multi-database in django
# add by WeizhongTu
DATABASE_ROUTERS = ['testproject.database_router.DatabaseAppsRouter']
DATABASE_APPS_MAPPING = {
    # example:
    #'app_name':'database_name',
    #'message': 'test1',
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

# STATIC_URL = '/static/'
# STATICFILE_URL = {
#     os.path.relpath(BASE_DIR,'static')
# }
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, "media").replace('\\','/')



