# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('address', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
            ],
            options={
                'verbose_name': '\u6c34\u53f8',
                'verbose_name_plural': '\u6c34\u53f8',
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('status', models.CharField(choices=[('online', '\u5728\u7ebf'), ('offline', '\u79bb\u7ebf')], max_length=8, verbose_name='\u72b6\u6001')),
                ('running', models.BooleanField(verbose_name='\u662f\u5426\u8fd0\u884c')),
                ('image', models.ImageField(blank=True, max_length=50, null=True, upload_to='station/%Y/%m', verbose_name='\u56fe\u7247')),
            ],
            options={
                'verbose_name': '\u673a\u6cf5',
                'verbose_name_plural': '\u673a\u6cf5',
            },
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='\u7f16\u53f7')),
                ('data', models.CharField(max_length=2000, verbose_name='\u6570\u636e')),
                ('datetime', models.DateTimeField(verbose_name='\u65f6\u95f4')),
                ('local', models.CharField(max_length=50, verbose_name='\u4f4d\u7f6e')),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pump.Pump', verbose_name='\u96b6\u5c5e\u673a\u6cf5')),
            ],
            options={
                'verbose_name': '\u9891\u8c31',
                'verbose_name_plural': '\u9891\u8c31',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u540d\u79f0')),
                ('address', models.CharField(max_length=100, verbose_name='\u5730\u5740')),
                ('image', models.ImageField(blank=True, max_length=50, null=True, upload_to='station/%Y/%m', verbose_name='\u56fe\u7247')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pump.Company', verbose_name='\u96b6\u5c5e\u6c34\u53f8')),
            ],
            options={
                'verbose_name': '\u6cf5\u7ad9',
                'verbose_name_plural': '\u6cf5\u7ad9',
            },
        ),
        migrations.AddField(
            model_name='pump',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pump.Station', verbose_name='\u96b6\u5c5e\u6cf5\u7ad9'),
        ),
    ]
