# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spectrum',
            name='pump',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='image',
        ),
        migrations.AddField(
            model_name='pump',
            name='pumpcode',
            field=models.CharField(default=1, max_length=50, verbose_name='\u7f16\u53f7'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Spectrum',
        ),
    ]
