# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0002_auto_20171225_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u8054\u7cfb\u65b9\u5f0f'),
        ),
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.FloatField(blank=True, default=0, verbose_name='\u7eac\u5ea6'),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.FloatField(blank=True, default=0, verbose_name='\u7ecf\u5ea6'),
        ),
    ]
