# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 11:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pump', '0003_auto_20180104_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='running',
        ),
        migrations.AddField(
            model_name='pump',
            name='beginUseDate',
            field=models.DateField(default=datetime.date.today, verbose_name='\u6295\u5165\u4f7f\u7528\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='pump',
            name='motorProductType',
            field=models.CharField(default='', max_length=50, verbose_name='\u7535\u673a\u578b\u53f7'),
        ),
        migrations.AddField(
            model_name='pump',
            name='motorPublishCode',
            field=models.CharField(default='', max_length=50, verbose_name='\u7535\u673a\u51fa\u5382\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='pump',
            name='motorPublishDate',
            field=models.DateField(default=datetime.date.today, verbose_name='\u7535\u673a\u51fa\u5382\u65e5\u671f'),
        ),
        migrations.AddField(
            model_name='pump',
            name='pumpProductType',
            field=models.CharField(default='', max_length=50, verbose_name='\u6c34\u6cf5\u578b\u53f7'),
        ),
        migrations.AddField(
            model_name='pump',
            name='pumpPublishCode',
            field=models.CharField(default='', max_length=50, verbose_name='\u6c34\u6cf5\u51fa\u5382\u7f16\u53f7'),
        ),
        migrations.AddField(
            model_name='pump',
            name='pumpPublishDate',
            field=models.DateField(default=datetime.date.today, verbose_name='\u6c34\u6cf5\u51fa\u5382\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u673a\u7ec4\u540d\u79f0'),
        ),
    ]
